// TODO(dromzeh): organize this, not a priority right now though
export const tableNames = {
    asset: "asset",
    authCredentials: "authCredentials",
    authSession: "authSession",
    authUser: "authUser",
    userFollowing: "userFollowing",
    userBlocked: "userBlocked",
    gameAssetCategory: "gameAssetCategory",
    assetLikes: "assetLikes",
    userCollectionLikes: "userCollectionLikes",
    userCollectionCollaborators: "userCollectionCollaborators",
    game: "game",
    gameLikes: "gameLikes",
    // atlas: "atlas",
    // atlasToAsset: "atlasToAsset",
    assetExternalFile: "assetExternalFile",
    assetTag: "assetTag",
    assetTagLikes: "assetTagLikes",
    assetTagAsset: "assetTagAsset",
    emailVerificationToken: "emailVerificationToken",
    passwordResetToken: "passwordResetToken",
    assetCategory: "assetCategory",
    assetCategoryLikes: "assetCategoryLikes",
    userFavorite: "userFavorite",
    userFavoriteAsset: "userFavoriteAsset",
    userCollection: "userCollection",
    userCollectionAsset: "userCollectionAsset",
    socialsConnection: "socialsConnection",
    requestForm: "requestForm",
    requestFormUpvotes: "requestFormUpvotes",
}
