// TODO(dromzeh): organize this, not a priority right now though
export const tableNames = {
    asset: "asset",
    authCredentials: "authCredentials",
    authSession: "authSession",
    authUser: "authUser",
    userFollowing: "userFollowing",
    userBlocked: "userBlocked",
    gameAssetCategory: "gameAssetCategory",
    assetLikes: "assetLikes",
    assetComments: "assetComments",
    assetCommentsLikes: "assetCommentsLikes",
    userCollectionLikes: "userCollectionLikes",
    userCollectionCollaborators: "userCollectionCollaborators",
    game: "game",
    gameLikes: "gameLikes",
    stripeUser: "stripeUser",
    assetExternalFile: "assetExternalFile",
    assetTag: "assetTag",
    assetTagLikes: "assetTagLikes",
    assetTagAsset: "assetTagAsset",
    emailVerificationToken: "emailVerificationToken",
    passwordResetToken: "passwordResetToken",
    assetCategory: "assetCategory",
    assetCategoryLikes: "assetCategoryLikes",
    userFavourite: "userFavourite",
    userFavouriteAsset: "userFavouriteAsset",
    userCollection: "userCollection",
    userCollectionAsset: "userCollectionAsset",
    socialsConnection: "socialsConnection",
    requestForm: "requestForm",
    requestFormUpvotes: "requestFormUpvotes",
}
